name: ViewPN
description: Demonstrates how to use the openvpn_flutter plugin. 
publish_to: 'none' 

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  openvpn_flutter: 
    path: ../ 
  cupertino_icons: ^1.0.2
  country_icons: ^2.0.2
  flutter_svg: ^1.1.0
  dart_ping: ^6.1.2
  shared_preferences: ^2.0.15
  provider: ^6.0.3
  http: ^0.13.4
  adaptive_theme: ^3.1.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^1.0.0
 
flutter: 
  uses-material-design: true 